# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import scoring_pb2 as scoring__pb2


class ScoringStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ScoreDetection = channel.unary_unary(
        '/scoringproto.Scoring/ScoreDetection',
        request_serializer=scoring__pb2.DetectionScoreRequest.SerializeToString,
        response_deserializer=scoring__pb2.DetectionScore.FromString,
        )


class ScoringServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ScoreDetection(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ScoringServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ScoreDetection': grpc.unary_unary_rpc_method_handler(
          servicer.ScoreDetection,
          request_deserializer=scoring__pb2.DetectionScoreRequest.FromString,
          response_serializer=scoring__pb2.DetectionScore.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'scoringproto.Scoring', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
